services:
    Brkwsky\Customer\Controller\ImportController:
        public: true
        arguments: ['@brkwsky.jobs.import', '@brkwsky.jobs.import.model']
        calls:
            - [setContainer, ['@service_container']]

    Brkwsky\Customer\EventListener\ExportLoopListener:
        public: true
        autoconfigure: true
        autowire: true